app:
  auto_sync_minutes: 0
  currency: EUR
  mock_mode: false
  vehicle_name: M3
evcc:
  api_token: ''
  host: evcc
  password: ''
  port: 7070
  use_tls: false
pricing_defaults:
  feedin_price_per_kwh: 0.08
  grid_price_per_kwh: 0.32
teslamate:
  api_token: ''
  url: http://teslamate:4000/api
